### PR TITLE
internal/lsp: fix encoding of unknown semantic token types

### LINKED ISSUE #763: Strange color highlighting
## Versions

This bug is reproducible in:
 - [x] the **latest** version of the extension (below)
 - [x] the **latest** version of the language server (below)

### Extension

```
HashiCorp Terraform
v2.14.0
```

### Language Server

```
Starting terraform-ls 0.21.0
```

### VS Code

```
1.60.0
```

### Operating System

```
Linux vrnnb-prc480 5.10.16.3-microsoft-standard-WSL2 hashicorp/vscode-terraform#1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux
```

### Terraform Version

```
Terraform v1.0.6
on linux_amd64
```

### Actual Behavior
image.

```tf
variable "read_replica_config" {
  type = list(
    object(
      {
        name                 = string,
        flavor               = string,
        availability_zone    = string,
        public_ips           = list(string),
        volume_type          = string,
        volume_encryption_id = string
      }
    )
  )
  description = "(optional)"
}
```
 

Reference: https://github.com/ansible/vscode-ansible/issues/175 (Maybe?)

### PR DESCRIPTION
**Pull request by radeksimko**
Fixes #763

## Before

156248451-7809c3e5-98ae-4b0c-a907-dc4a2817f631

## After

Screenshot 2022-03-02 at 09 05 12

## Follow up issues

 - https://github.com/hashicorp/vscode-terraform/issues/955
 - https://github.com/hashicorp/terraform-ls/issues/816

### CODE REVIEW

File: internal/lsp/token_encoder_test.go [hunk 1]
```diff
@@ -80,6 +80,59 @@ func TestTokenEncoder_singleLineTokens(t *testing.T) {
 	}
 }
 
+func TestTokenEncoder_unknownTokenType(t *testing.T) {
```
Comment (dbanck) [inline internal/lsp/token_encoder_test.go:83]: I'm unsure if this test case covers the bug in https://github.com/hashicorp/terraform-ls/issues/763. If I undo the changes in `internal/lsp/token_encoder.go`, it still passes. Should we extend the test?

Comment (radeksimko) [reply internal/lsp/token_encoder_test.go:83]: Test modified, thanks for the catch!

**Review by dbanck — APPROVED** [review]
Nice! 👍
